name: 📦👷‍♂️ CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: 📦 release tags on GitHub
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:

    - uses: actions/checkout@v2

    - name: ⬇ setup .net 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: 🔨 build
      run: dotnet build -c Release -o dist

    - name: 🤏 zip binaries
      run: Compress-Archive -Path .\dist\* -DestinationPath "hyperactive-$($env:GITHUB_REF -replace "refs/tags/v").zip"

    - name: 📦 release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          hyperactive-*.zip
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
